-- STEPH 2, PROSES IMPORT DATA MELALUI TABLE DATA IMPORT WIZZAR SECARA OTOMATIS SUDAH SELESAI, KARENA DATA NYA SUDAH READY
-- STEPH 3, PROSES PENGECEKAN DATA YANG SUDAH DI IMPORT UNTUK MEMASTIKAN APAKAH DATA NYA AMAN ATAU ADA YANG EROR

-- TAHAP PENGECEKAN TABEL --
-- 1. PROSES PENGECEKAN TABEL PERUSAHAAN UNTUK MELIHAT DATA DARI TABLE PERUSAHAAN
SELECT * FROM perusahaan; -- TIDAK ADA KENDALA

-- 2. PROSES PENGECEKAN TABEL PELANGGAN UNTUK MELIHAT DATA DARI TABLE PELANGGAN
SELECT * FROM pelanggan; -- TIDAK ADA KENDALA

-- 3. PROSES PENGECEKAN TABEL PRODUKSI UNTUK MELIHAT DATA DARI TABLE PRODUKSI
SELECT * FROM produk; -- TIDAK ADA KENDALA

-- 4. PROSES PENGECEKAN TABEL TRANSAKSI UNTUK MELIHAT DATA DARI TABLE TRANSAKSI
SELECT * FROM transaksi; -- TIDAK ADA KENDALA

-- TAHAP PENGECEKAN RECORD DI SETIAP TABEL --
SELECT COUNT(*) FROM perusahaan; -- BERDASARKAN HASIL RECORD COUNT TERDIRI DARI 50 COUNT
SELECT COUNT(*) FROM pelanggan; -- BERDASARKAN HASIL RECORD COUNT TERDIRI DARI 2000 COUNT
SELECT COUNT(*) FROM produk; -- BERDASARKAN HASIL RECORD COUNT TERDIRI DARI 300 COUNT
SELECT COUNT(*) FROM transaksi; -- BERDASARKAN HASIL RECORD COUNT TERDIRI DARI 8650 COUNT

-- TAHAP PENGECEKAN MELALUI PERINTAH 10 DATA TERATAS --
SELECT * FROM perusahaan LIMIT 10; -- TIDAK ADA KENDALA
SELECT * FROM produk LIMIT 10; -- TIDAK ADA KENDALA
SELECT * FROM pelanggan LIMIT 10; -- TIDAK ADA KENDALA
SELECT * FROM transaksi LIMIT 10; -- TIDAK ADA KENDALA



